name: Awesome CI/CD

on:
    push:
        branches: ['master']
        tags: ['v[0-9]+.[0-9]+.[0-9]*']

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    MANIFEST_FILE: c1-freeswitch-deploy.yaml

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      TOKEN= ${{ secrets.SIGNALWIRE_TOKEN }}


            # - name: Checkout ops repo
            #   uses: actions/checkout@v4
            #   with:
            #       repository: c1-ab/c1-ops
            #       path: ./c1-ops
            #       token: ${{ secrets.OPS_ACCESS_TOKEN }}

            # - name: Set vars for dev
            #   if: ${{ github.ref_type == 'branch' }}
            #   run: |
            #       echo "IMAGE_VERSION=${GITHUB_SHA::7}" >> "$GITHUB_ENV"
            #       echo "MANIFEST_DIR=c1-dev" >> "$GITHUB_ENV"

            # - name: Set vars for stage
            #   if: ${{ github.ref_type == 'tag' }}
            #   run: |
            #       echo "IMAGE_VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
            #       echo "MANIFEST_DIR=c1-stage" >> "$GITHUB_ENV"

            # - name: Update version in ops repo
            #   run: |
            #       git config --global user.name github-actions
            #       git config --global user.email github-actions@github.com
            #       cd c1-ops
            #       sed -i "s,image:.*$,image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_VERSION}," ${MANIFEST_DIR}/${{ env.MANIFEST_FILE }}
            #       git add .
            #       git commit -m "github actions updating version"
            #       git push
